### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Siuming93** [yh1094632455/Unity-client-skynet-server#1]
> 64位ubuntu16.04版

在skynet 目录下执行 ./skynet ../config/loginserver.cfg 命令时,提示:
......
---start login server---
[:0100000b] init service failed: error loading module 'protobuf.c'  from file './luaclib/protobuf.so':
    ./luaclib/protobuf.so: wrong ELF class: ELFCLASS32
......

**Comment by yh1094632455** [comment]
请问下你的Ubuntu是64位的么？

**Comment by yh1094632455** [comment]
@Siuming93 你的ubuntu应该是64位的吧，你试试安装32位的试试或者你自己编译一个64 位的protobuf.so ,然后启动的时候还需要修改mysql的的地址端口啥的，具体在 loginserver 里面的dbserver.lua文件
